### ISSUE TITLE
Go version used for binary

### ISSUE THREAD

**Issue by saich** [bitnami/bitnami-docker-oauth2-proxy#10]
Is there a way to find which version of Go is used to build the binary?

We're looking a security issue related to HTTP Request smuggling while using this docker image, and we're suspecting it to be related to Golang version.

**Comment by alemorcuq** [comment]
Hi, @saich.

We don't build the `oauth2_proxy` binary ourselves, we package the [upstream one from their repository](https://github.com/pusher/oauth2_proxy/releases/). Looking at that page, it looks like it is built using Go version `1.12.1`.

I'm interested in this security issue. Do you have any link where I can read about it?

Regards,
Alejandro

**Comment by vijithv** [comment]
You can read about HTTP request smuggling vulnerability here: https://portswigger.net/research/http-desync-attacks-request-smuggling-reborn

Basically, this issue _can_ arise when there are issues with header parsing logic in server implementations. For example, we were using a pretty old version of `oauth2-proxy` in production and upon testing, we've observed that it is treating a supposedly invalid header - `Transfer-Encoding : chunked`(with a space in header name) as a valid one and hence computing the request boundary differently than other systems (like load balancer) in the pipeline. Hence the vulnerability (Of course there are conditions to be met to reproduce this like having a `Content-Length` header etc. Above link has the details).

Now, we tried deploying the latest versions of `oauth2-proxy` from `bitnami` (bitnami/oauth2-proxy:latest) and they still have the same issue. But when we tried building different tags of `oauth2-proxy` from [pusher](https://github.com/pusher/oauth2_proxy) (3.1.0, 3.2.0, 4.0.0), we have observed that from `3.2.0` this issue is fixed and it now throws a `400 Bad Request: invalid header name` when given such a header. In `3.2.0` the golang version got changed from `golang:1.11-stretch` to `golang:1.12-stretch`. We have even tried updating the Dockerfile in `3.1.0` to use `golang:1.12-stretch` and it fixes the issue.

What we are not sure about though is if `bitnami` is using the latest from `pusher` for its images, how is it showing different behavior.

**Comment by alemorcuq** [comment]
Thank you for your detailed response, @vijithv. I can explain why the behaviour is different in both cases.

At the moment, we are packaging the upstream binary for `oauth2_proxy`. We get it from the [pusher repository on GitHub](https://github.com/pusher/oauth2_proxy/releases/): there you can see a `.tar.gz` file with the binaries for Linux amd64: `oauth2_proxy-v4.0.0.linux-amd64.go1.12.1.tar.gz`. According to the name of the file, it looks like it's built using Go 1.12.1.

On the other hand, the Dockerfile from pusher is building `oauth2_proxy` from source instead, using the Go version specified at the top. `golang:1.12-stretch` is using a rolling tag, meaning that it always points to the latest 1.12 release with Debian Stretch. If you build it today, `golang:1.12-stretch` will get `golang:1.12.10-stretch`. [You can see all the tags here](https://hub.docker.com/_/golang). This explains the different behaviour between the two images.

Usually, for Go projects, we trust that upstream will keep the binaries they publish up to date. Given the situation, I've created an internal task to analyze this and decide if we want to build `oauth2_proxy` from source instead of packaging the binary.

We will update this issue when there are any news. Thank you again for reporting this.

Regards,
Alejandro

**Comment by vijithv** [comment]
@alemorcuq Thanks for the confirmation. That explains the discrepancy. Seems like the issue is with Golang versions `1.12.9` and `1.13` and is fixed in `1.12.10` and `1.13.1`.

**Comment by saich** [comment]
Corresponding links:

- https://nvd.nist.gov/vuln/detail/CVE-2019-16276
- https://github.com/golang/go/issues/34540

**Comment by juan131** [comment]
Hi @vijithv @saich 

Thanks so much for the information. I'll try to raise the priority of the associated task so we address this vulnerability.

**Comment by alemorcuq** [comment]
Hi, @saich, @vijithv.

We are now building `oauth2_proxy` from source using Go 1.12.13. The following release tags include the new binary:

- `4.0.0-ol-7-r91`
- `4.0.0-debian-9-r81`

Thank you very much for bringing this to our attention. Let us know if you have any other issues.

Regards,
Alejandro

**Comment by saich** [comment]
@alemorcuq That's great. Thanks for the update.
