### ISSUE TITLE
Feature request: provide tag for minor versions

### ISSUE THREAD

**Issue by johanfleury** [bitnami/bitnami-docker-oauth2-proxy#20]
**Description**

oauth2-proxy is versioned using what looks like semver with a `<major>.<minor>.<patch>` pattern. Currently the container images are tagged with the major version and the patch version (i.e: `bitnami/oauth2-proxy:7` and `bitnami/oauth2-proxy:7.2.0`).

It would be great to have a tag for the minor version (i.e `bitnami/oauth2-proxy:7.2`). This would allow people using docker-compose (or Kubernetes with `imagePullPolicy: Always`) to have some kind of version constraint on the minor release.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for spotting this out. 
  I am creating an internal task in order to handle the versioning.
  We will come back as soon as we have news.

**Comment by fmulero** [comment]
Hi @johanfleury 

I was reviewing the internal notes about this topic, I'm afraid, there is no easy way to implement this feature in our current release process. The reason behind is that we are supporting a bunch of projects that are not using semver . More information about our current tags [here](https://docs.bitnami.com/tutorials/understand-rolling-tags-containers/)

We are also moving to [a new repository](https://github.com/bitnami/containers) in order to be aligned with the approach followed in [bitnami/charts](https://github.com/bitnami/charts). More information [here](https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html). If you are still interested on this feature, please open a new issue in [bitnami/containers](https://github.com/bitnami/containers) repository
