### ISSUE TITLE
email-domain parameter not read

### ISSUE THREAD

**Issue by driesken** [bitnami/bitnami-docker-oauth2-proxy#3]
I've just pulled the image and created the instance using the following statement:
```
docker create --name=oauth2-proxy --net=host -p 8080:8080 -p 4180:4180 --restart=always -e VERSION=latest -e PUID=1000 -e PGID=1000 -e TZ=Europe/Brussels -e email-domain=* -e OAUTH2_PROXY_COOKIE_SECRET=<cookiescret> -e OAUTH2_PROXY_CLIENT_ID=<clientid> -e OAUTH2_PROXY_CLIENT_SECRET=u<secret> -v /docker/containers/oauth2-proxy/config:/config bitnami/oauth2-proxy:latest
```

However, according to the logs it can't seem to read the "email-domain" parameter:
```
2018/07/03 08:41:30 main.go:103: Invalid configuration:
  missing setting for email validation: email-domain or authenticated-emails-file required.
      use email-domain=* to authorize all email addresses
```

Is there another option that I have to use?

**Comment by marcosbc** [comment]
Hi,

Since `email-domain` is a CLI parameter to the `oauth2_proxy` binary, and we already specify CLI parameters in the Dockerfile, you are forced to specify all of them again plus the new `email-domain` parameter.

In your case, you would run the following command:

    docker create --name=oauth2-proxy --net=host -p 8080:8080 -p 4180:4180 --restart=always -e VERSION=latest -e PUID=1000 -e PGID=1000 -e TZ=Europe/Brussels -e OAUTH2_PROXY_COOKIE_SECRET=<cookiescret> -e OAUTH2_PROXY_CLIENT_ID=<clientid> -e OAUTH2_PROXY_CLIENT_SECRET=u<secret> -v /docker/containers/oauth2-proxy/config:/config bitnami/oauth2-proxy:latest --upstream=http://0.0.0.0:8080/ --http-address=0.0.0.0:4180 --email-domain=*

We understand this is not ideal, and have started discussions for improving this specific container image.

**Comment by driesken** [comment]
Thanks, the docker instance is working now!
